version: '3'
services:
  frontend:
    image: kyawmyotun/lhankyi_frontend:latest
    ports:
      - 5000:5000
    environment:
      PORT: 5000
  backend:
    image: kyawmyotun/lhankyi:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/postgres
      - JWT_SECRECT=onepluseoneisthree
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRE_DB=postgres
